name: Java-Maven-Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Reusable step for common setup tasks
  setup:
    runs-on: ubuntu-latest
    outputs:
      java_version: '21'  # Adjust this if necessary

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

  bump-version:
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      java_version: ${{ steps.get_version.outputs.java_version }}
    steps:
      - name: Get and Bump Java Version
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF = $NF + 1 ; print}')
          echo "Bumping version from $VERSION to $NEW_VERSION"
          mvn versions:set -DnewVersion=$NEW_VERSION -DgenerateBackupPoms=false
          echo "java_version=$NEW_VERSION" >> $GITHUB_ENV
          echo "java_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit and Push Updated Version
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add pom.xml
          git commit -m "Bump version to ${{ steps.get_version.outputs.java_version }}"
          git push origin ${{ github.ref }}

  build:
    needs: bump-version
    runs-on: ubuntu-latest
    permissions:
      packages: read
    outputs:
      tag: ${{ steps.create_tag.outputs.tag }}
      jar_path: ${{ steps.build_maven.outputs.jar_path }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Setup Maven Settings for GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo "<servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers>" > ~/.m2/settings.xml

      - name: Build with Maven
        id: build_maven
        run: |
          mvn clean install
          # Set the path to the generated .jar file
          JAR_PATH=$(find target -name "*.jar" | head -n 1)
          echo "jar_path=$JAR_PATH" >> $GITHUB_ENV
          echo "jar_path=$JAR_PATH" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Git Tag
        id: create_tag
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          TAG="v${{ needs.bump-version.outputs.java_version }}"
          echo "tag=$TAG" >> $GITHUB_ENV
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build.outputs.tag }}
          files: ${{ needs.build.outputs.jar_path }}
          body: |
            ### New Release ${{ needs.build.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

