name: Build Verification

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
        uses: actions/checkout@v4
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Build with Maven
        run: mvn clean install -B
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: mvn test
